spring.application.name=FoodlyIdentityService

# Servidor
server.port=8081

# Base de Datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/foodly_identity_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret.key=f00dlyS3cr3tK3yF0rFoodN0d3Pl4tf0rm2025Lima
jwt.issuer=foodly-identity-service
jwt.expiration.minutes=60

# Springdoc OpenAPI (Swagger UI)
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/openapi-ui

# ActiveMQ
spring.activemq.broker-url=vm://localhost?broker.persistent=false
spring.jms.pub-sub-domain=false
